sudo: required
dist: trusty
language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository ppa:paparazzi-uav/ppa -y
  - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
  - sudo apt-get update -q
install:
  - sudo apt-get install -y --force-yes paparazzi-dev paparazzi-jsbsim gcc-arm-embedded gcc-arm-linux-gnueabi libipc-run-perl rustc cargo
script:
  - arm-none-eabi-gcc --version
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then if [ "${TRAVIS_EVENT_TYPE}" == "cron" ]; then make test_all_confs; else make test; fi; fi

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "CxbyPLaOnUlOfcjn5+ArDstEXOQiFJT3fzflBRuQh9MaES7LmoOCK0nRAkvV6MhAPNy7frflpPwzL2lmTbxCwo2fE8WtTTdc/0UoupqKr3ChP7bbmHbyr9Y9BrORBuXVAAeDEMhIa3x3Uu82WkOUQI4Bj1WSlGMV/u1R977ud4k="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "paparazzi/paparazzi"
      description: "Build submitted via Travis CI"
    notification_email: paparazzi-builds@nongnu.org
    build_command_prepend: make ext; cov-configure --comptype gcc --compiler arm-none-eabi-gcc --template
    build_command: make test_coverity
    branch_pattern: coverity_scan

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4187f8dda7a22a92b749
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
